"""
Code Runner module for executing Python code generated by AI models.
"""
import io
import sys
import contextlib
import traceback
from typing import Dict, Tuple, Any
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

class CodeRunner:
    @staticmethod
    def extract_code_blocks(text: str) -> list:
        """Extract Python code blocks from markdown-formatted text."""
        import textwrap
        
        patterns = [
            r"```python\s*\n(.*?)\n\s*```",
            r"```py\s*\n(.*?)\n\s*```"
        ]
        
        code_blocks = []
        for pattern in patterns:
            matches = re.findall(pattern, text, re.DOTALL)
            for match in matches:
                # Remove common leading whitespace (dedent)
                cleaned_code = textwrap.dedent(match).strip()
                if cleaned_code and not cleaned_code.startswith('```'):
                    code_blocks.append(cleaned_code)
        
        return code_blocks
    
    @staticmethod
    def detect_llm_code(text: str) -> bool:
        """Detect if LLM response contains executable Python code."""
        # Check for code blocks
        if '```python' in text or '```' in text:
            return True
        
        # Check for common Python patterns
        python_patterns = [
            r'import\s+\w+', r'from\s+\w+\s+import',
            r'def\s+\w+\(', r'class\s+\w+',
            r'pd\.', r'np\.', r'plt\.', r'px\.',
            r'DataFrame\(', r'\.plot\(', r'\.show\(',
            r'print\(', r'fig\s*=', r'df\s*=',
            r'data\s*=', r'\.head\(', r'\.describe\(',
            r'\.groupby\(', r'\.agg\(', r'\.apply\('
        ]
        
        for pattern in python_patterns:
            if re.search(pattern, text, re.IGNORECASE):
                return True
        
        return False
    
    @staticmethod
    def execute_code(code: str, globals_dict: Dict[str, Any] = None, locals_dict: Dict[str, Any] = None) -> Dict[str, Any]:
        """Execute Python code and capture output."""
        if globals_dict is None:
            globals_dict = {}
        if locals_dict is None:
            locals_dict = {}
            
        # Add common imports and data to globals
        globals_dict.update({
            'pd': pd,
            'np': np,
            'px': px,
            'go': go,
            'plt': plt,
            'make_subplots': make_subplots,
        })
        
        # Capture stdout
        old_stdout = sys.stdout
        sys.stdout = captured_output = io.StringIO()
        
        try:
            # Execute the code
            exec(code, globals_dict, locals_dict)
            
            # Get the last expression result if available
            result = None
            try:
                # Try to evaluate the last line as an expression
                lines = code.strip().split('\n')
                if lines:
                    last_line = lines[-1].strip()
                    if last_line and not any(last_line.startswith(kw) for kw in 
                                           ['import', 'from', 'def', 'class', 'if', 'for', 'while', 'try', 'with', 'print']):
                        # Check if it's a simple expression that can be evaluated
                        try:
                            result = eval(last_line, globals_dict, locals_dict)
                        except:
                            pass
            except:
                pass
            
            output = captured_output.getvalue()
            return {"result": result, "output": output, "success": True}
            
        except Exception as e:
            output = captured_output.getvalue()
            error_output = f"{output}\n{traceback.format_exc()}" if output else traceback.format_exc()
            return {"result": None, "output": error_output, "success": False}
        finally:
            sys.stdout = old_stdout
    
    @staticmethod
    def handle_plotly_figure(result) -> Tuple[bool, Any]:
        """Check if the result is a Plotly figure."""
        try:
            if isinstance(result, go.Figure):
                return True, result
            # Also check for plotly express figures
            if hasattr(result, 'data') and hasattr(result, 'layout') and hasattr(result, 'show'):
                return True, result
        except Exception:
            pass
        return False, None

    @staticmethod
    def handle_matplotlib_figure(result) -> Tuple[bool, Any]:
        """Check if the result is a Matplotlib figure."""
        try:
            if hasattr(result, 'savefig') and hasattr(result, 'show'):
                return True, result
        except Exception:
            pass
        return False, None

    @staticmethod
    def handle_pandas_dataframe(result) -> Tuple[bool, pd.DataFrame]:
        """Check if the result is a Pandas DataFrame."""
        if isinstance(result, pd.DataFrame):
            return True, result
        return False, None
    
    @staticmethod
    def handle_pandas_series(result) -> Tuple[bool, pd.Series]:
        """Check if the result is a Pandas Series."""
        if isinstance(result, pd.Series):
            return True, result
        return False, None
    
    @staticmethod
    def handle_numpy_array(result) -> Tuple[bool, np.ndarray]:
        """Check if the result is a NumPy array."""
        if isinstance(result, np.ndarray):
            return True, result
        return False, None
        
    @staticmethod
    def run_llm_code_blocks(llm_response: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """Execute all code blocks found in LLM response with state preservation."""
        code_blocks = CodeRunner.extract_code_blocks(llm_response)
        
        if not code_blocks:
            return {"has_code": False, "executed_blocks": [], "dataframes": [], "figures": [], "series": [], "arrays": [], "matplotlib_figures": []}
        
        results = {
            "has_code": True,
            "executed_blocks": [],
            "dataframes": [],
            "figures": [],
            "series": [],
            "arrays": [],
            "matplotlib_figures": []
        }
        
        # Shared global and local scope for state preservation between blocks
        shared_globals = {
            'pd': pd,
            'np': np,
            'px': px,
            'go': go,
            'plt': plt,
            'make_subplots': make_subplots,
            **data
        }
        shared_locals = {}
        
        for i, code in enumerate(code_blocks):
            try:
                block_result = CodeRunner.execute_code(code, shared_globals, shared_locals)
                
                # Check for different data types in the execution result
                is_dataframe, df_result = CodeRunner.handle_pandas_dataframe(block_result["result"])
                is_figure, fig_result = CodeRunner.handle_plotly_figure(block_result["result"])
                is_matplotlib_figure, mpl_result = CodeRunner.handle_matplotlib_figure(block_result["result"])
                is_series, series_result = CodeRunner.handle_pandas_series(block_result["result"])
                is_array, array_result = CodeRunner.handle_numpy_array(block_result["result"])
                
                # Add results to their respective lists
                if is_dataframe and df_result is not None:
                    results["dataframes"].append(df_result)
                if is_figure and fig_result is not None:
                    results["figures"].append(fig_result)
                if is_matplotlib_figure and mpl_result is not None:
                    results["matplotlib_figures"].append(mpl_result)
                if is_series and series_result is not None:
                    results["series"].append(series_result)
                if is_array and array_result is not None:
                    results["arrays"].append(array_result)
                
                # Also check shared_locals for any DataFrames, figures, etc. that were created
                for var_name, var_value in shared_locals.items():
                    if not var_name.startswith('_'):  # Skip private variables
                        df_check, df_val = CodeRunner.handle_pandas_dataframe(var_value)
                        if df_check and df_val is not None:
                            # Check if this DataFrame is already in results (by comparing shape and first few values)
                            already_exists = False
                            for existing_df in results["dataframes"]:
                                try:
                                    if (df_val.shape == existing_df.shape and 
                                        len(df_val) > 0 and len(existing_df) > 0 and
                                        df_val.iloc[0].equals(existing_df.iloc[0])):
                                        already_exists = True
                                        break
                                except:
                                    pass
                            if not already_exists:
                                results["dataframes"].append(df_val)
                        
                        fig_check, fig_val = CodeRunner.handle_plotly_figure(var_value)
                        if fig_check and fig_val is not None and fig_val not in results["figures"]:
                            results["figures"].append(fig_val)
                        
                        mpl_check, mpl_val = CodeRunner.handle_matplotlib_figure(var_value)
                        if mpl_check and mpl_val is not None and mpl_val not in results["matplotlib_figures"]:
                            results["matplotlib_figures"].append(mpl_val)
                        
                        series_check, series_val = CodeRunner.handle_pandas_series(var_value)
                        if series_check and series_val is not None:
                            # Check if this Series is already in results
                            already_exists = False
                            for existing_series in results["series"]:
                                try:
                                    if series_val.equals(existing_series):
                                        already_exists = True
                                        break
                                except:
                                    pass
                            if not already_exists:
                                results["series"].append(series_val)
                        
                        array_check, array_val = CodeRunner.handle_numpy_array(var_value)
                        if array_check and array_val is not None:
                            # Check if this array is already in results
                            already_exists = False
                            for existing_array in results["arrays"]:
                                try:
                                    if np.array_equal(array_val, existing_array):
                                        already_exists = True
                                        break
                                except:
                                    pass
                            if not already_exists:
                                results["arrays"].append(array_val)
                
                results["executed_blocks"].append({
                    "code": code,
                    "result": block_result["result"],
                    "output": block_result["output"],
                    "success": block_result["success"],
                    "is_dataframe": is_dataframe,
                    "is_figure": is_figure,
                    "is_matplotlib_figure": is_matplotlib_figure,
                    "is_series": is_series,
                    "is_array": is_array
                })
                
            except Exception as e:
                results["executed_blocks"].append({
                    "code": code,
                    "result": None,
                    "output": f"Error executing block {i+1}: {str(e)}",
                    "success": False,
                    "is_dataframe": False,
                    "is_figure": False,
                    "is_matplotlib_figure": False,
                    "is_series": False,
                    "is_array": False
                })
        
        return results

    @staticmethod  
    def display_streamlit_results(code_results: Dict[str, Any], st_module) -> None:
        """Enhanced display method for Streamlit with comprehensive data type support."""
        if not code_results.get("has_code", False):
            st_module.info("No executable code found in the response.")
            return
        
        # Track counters for different data types
        dataframe_counter = 0
        series_counter = 0
        array_counter = 0
        plotly_figure_counter = 0
        matplotlib_figure_counter = 0
        
        for i, block in enumerate(code_results["executed_blocks"]):
            with st_module.expander(f"📋 Code Block {i+1}", expanded=True):
                st_module.code(block["code"], language="python")
                
                if not block["success"]:
                    st_module.error("❌ Execution Error:")
                    st_module.code(block["output"], language="text")
                    continue
                
                # Display console output
                if block["output"] and block["output"].strip():
                    st_module.subheader("📄 Console Output:")
                    st_module.text(block["output"])
                
                # Display DataFrames
                if block.get("is_dataframe", False):
                    if code_results["dataframes"] and dataframe_counter < len(code_results["dataframes"]):
                        df = code_results["dataframes"][dataframe_counter]
                        st_module.subheader(f"📊 DataFrame Result {dataframe_counter + 1}:")
                        
                        # DataFrame metrics
                        col1, col2, col3 = st_module.columns(3)
                        with col1:
                            st_module.metric("Rows", df.shape[0])
                        with col2:
                            st_module.metric("Columns", df.shape[1])
                        with col3:
                            st_module.metric("Memory", f"{df.memory_usage(deep=True).sum():,} bytes")
                        
                        # Display DataFrame
                        st_module.dataframe(df, use_container_width=True)
                        
                        # Download button
                        csv_data = df.to_csv(index=False)
                        st_module.download_button(
                            label=f"💾 Download DataFrame {dataframe_counter + 1} as CSV",
                            data=csv_data,
                            file_name=f"dataframe_{dataframe_counter + 1}.csv",
                            mime="text/csv"
                        )
                        
                        # Basic statistics if numeric columns exist
                        numeric_cols = df.select_dtypes(include=[np.number]).columns
                        if len(numeric_cols) > 0:
                            with st_module.expander(f"📈 DataFrame {dataframe_counter + 1} Statistics"):
                                st_module.dataframe(df[numeric_cols].describe(), use_container_width=True)
                        
                        dataframe_counter += 1
                
                # Display Pandas Series
                if block.get("is_series", False):
                    if code_results.get("series") and series_counter < len(code_results["series"]):
                        series = code_results["series"][series_counter]
                        st_module.subheader(f"📊 Series Result {series_counter + 1}:")
                        
                        # Convert Series to DataFrame for display
                        series_df = series.to_frame().reset_index()
                        st_module.dataframe(series_df, use_container_width=True)
                        
                        # Series info
                        col1, col2 = st_module.columns(2)
                        with col1:
                            st_module.metric("Length", len(series))
                        with col2:
                            st_module.metric("Data Type", str(series.dtype))
                        
                        series_counter += 1
                
                # Display NumPy Arrays
                if block.get("is_array", False):
                    if code_results.get("arrays") and array_counter < len(code_results["arrays"]):
                        array = code_results["arrays"][array_counter]
                        st_module.subheader(f"🔢 NumPy Array {array_counter + 1}:")
                        
                        # Array info
                        col1, col2, col3 = st_module.columns(3)
                        with col1:
                            st_module.metric("Shape", str(array.shape))
                        with col2:
                            st_module.metric("Data Type", str(array.dtype))
                        with col3:
                            st_module.metric("Size", array.size)
                        
                        # Display array content based on size and dimensions
                        if array.size <= 1000:  # Small arrays
                            if array.ndim == 1:
                                array_df = pd.DataFrame({"Index": range(len(array)), "Value": array})
                                st_module.dataframe(array_df, use_container_width=True)
                            elif array.ndim == 2:
                                array_df = pd.DataFrame(array)
                                st_module.dataframe(array_df, use_container_width=True)
                            else:
                                st_module.text(str(array))
                        else:  # Large arrays - show summary
                            st_module.text(f"Array preview (first 10 elements): {array.flat[:10]}")
                        
                        array_counter += 1
                
                # Display Plotly figures
                if block.get("is_figure", False):
                    if code_results["figures"] and plotly_figure_counter < len(code_results["figures"]):
                        fig = code_results["figures"][plotly_figure_counter]
                        st_module.subheader(f"📈 Plotly Visualization {plotly_figure_counter + 1}:")
                        st_module.plotly_chart(fig, use_container_width=True)
                        plotly_figure_counter += 1
                
                # Display Matplotlib figures
                if block.get("is_matplotlib_figure", False):
                    if code_results.get("matplotlib_figures") and matplotlib_figure_counter < len(code_results["matplotlib_figures"]):
                        fig = code_results["matplotlib_figures"][matplotlib_figure_counter]
                        st_module.subheader(f"📊 Matplotlib Visualization {matplotlib_figure_counter + 1}:")
                        st_module.pyplot(fig)
                        matplotlib_figure_counter += 1
                
                # Display other result values
                if (block["result"] is not None and 
                    not any([block.get("is_dataframe"), block.get("is_series"), 
                            block.get("is_array"), block.get("is_figure"), 
                            block.get("is_matplotlib_figure")])):
                    st_module.subheader("🔢 Result Value:")
                    
                    if isinstance(block["result"], (list, dict)):
                        st_module.json(block["result"])
                    elif isinstance(block["result"], (int, float)):
                        st_module.metric("Result", block["result"])
                    elif isinstance(block["result"], str):
                        if len(block["result"]) > 1000:
                            st_module.text_area("Result:", block["result"], height=200)
                        else:
                            st_module.text(block["result"])
                    elif hasattr(block["result"], "_repr_html_"):
                        # For objects with HTML representation
                        st_module.html(block["result"]._repr_html_())
                    else:
                        st_module.text(str(block["result"]))
        
        # Summary section for multiple results
        if len(code_results["executed_blocks"]) > 1:
            st_module.markdown("---")
            st_module.subheader("📋 Execution Summary")
            
            successful_blocks = sum(1 for block in code_results["executed_blocks"] if block["success"])
            total_blocks = len(code_results["executed_blocks"])
            
            col1, col2, col3, col4, col5 = st_module.columns(5)
            with col1:
                st_module.metric("✅ Successful", successful_blocks)
            with col2:
                st_module.metric("📊 DataFrames", len(code_results.get("dataframes", [])))
            with col3:
                st_module.metric("📈 Charts", len(code_results.get("figures", [])) + len(code_results.get("matplotlib_figures", [])))
            with col4:
                st_module.metric("📊 Series", len(code_results.get("series", [])))
            with col5:
                st_module.metric("🔢 Arrays", len(code_results.get("arrays", [])))

    @staticmethod
    def auto_execute_llm_response(llm_response: str, data: Dict[str, Any], st_module=None) -> Dict[str, Any]:
        """Automatically detect and execute code in LLM response, then display results."""
        # Check if response contains code
        if not CodeRunner.detect_llm_code(llm_response):
            return {"has_code": False, "message": "No executable code detected in response."}
        
        # Execute the code
        results = CodeRunner.run_llm_code_blocks(llm_response, data)
        
        # Display results if Streamlit module is provided
        if st_module is not None and results.get("has_code", False):
            st_module.subheader("🚀 Code Execution Results")
            CodeRunner.display_streamlit_results(results, st_module)
        
        return results
